name: OpenTofu Destroy Pipeline

on:
    workflow_dispatch:

concurrency:
    group: opentofu-destroy-${{ github.ref }}
    cancel-in-progress: false

jobs:
    destroy:
        runs-on: ubuntu-latest

        env:
            OPENTOFU_VERSION: 1.7.0
            AWS_REGION: de-fra1

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1
              with:
                  tofu_version: ${{ env.OPENTOFU_VERSION }}

            - name: OpenTofu Init
              run: tofu init -upgrade -reconfigure
              env:
                  UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
                  UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: OpenTofu Plan Destroy
              run: tofu plan -destroy -no-color
              env:
                  UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
                  UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: OpenTofu Destroy
              run: tofu destroy -auto-approve
              env:
                  UPCLOUD_USERNAME: ${{ secrets.UPCLOUD_USERNAME }}
                  UPCLOUD_PASSWORD: ${{ secrets.UPCLOUD_PASSWORD }}
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
